// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_NETLISTROLLER_H
#define _UI_COMP_NETLISTROLLER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT NetListRoller
#define UI_COMP_NETLISTROLLER_NETLISTROLLER 0
#define _UI_COMP_NETLISTROLLER_NUM 1
lv_obj_t * ui_NetListRoller_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
