// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT NetListRoller

lv_obj_t * ui_NetListRoller_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_NetListRoller;
    cui_NetListRoller = lv_roller_create(comp_parent);
    lv_roller_set_options(cui_NetListRoller, "empty", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(cui_NetListRoller, 122);
    lv_obj_set_height(cui_NetListRoller, 113);
    lv_obj_set_x(cui_NetListRoller, -85);
    lv_obj_set_y(cui_NetListRoller, 0);
    lv_obj_set_align(cui_NetListRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(cui_NetListRoller, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_NetListRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_NetListRoller, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_NetListRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_NetListRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_NetListRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_NetListRoller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(cui_NetListRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_NetListRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_NetListRoller, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_NetListRoller, lv_color_hex(0x2D27A8), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_NetListRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NETLISTROLLER_NUM);
    children[UI_COMP_NETLISTROLLER_NETLISTROLLER] = cui_NetListRoller;
    lv_obj_add_event_cb(cui_NetListRoller, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_NetListRoller, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_NetListRoller_create_hook(cui_NetListRoller);
    return cui_NetListRoller;
}

