// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_BGImg;
extern lv_obj_t * ui_RollerLicuidGlass;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_InfoLicuidGlass;
extern lv_obj_t * ui_MainIfonLabel;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_HumLabel;
extern lv_obj_t * ui_PressLabel;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_TempValLabel;
extern lv_obj_t * ui_HumValLabel;
extern lv_obj_t * ui_PressValLabel;
extern lv_obj_t * ui_BatChargeBar;
extern lv_obj_t * ui_BatChargeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

