// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_BGImg = NULL;
lv_obj_t * ui_RollerLicuidGlass = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_InfoLicuidGlass = NULL;
lv_obj_t * ui_MainIfonLabel = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_HumLabel = NULL;
lv_obj_t * ui_PressLabel = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_TempValLabel = NULL;
lv_obj_t * ui_HumValLabel = NULL;
lv_obj_t * ui_PressValLabel = NULL;
lv_obj_t * ui_BatChargeBar = NULL;
lv_obj_t * ui_BatChargeLabel = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_MainScreen, &ui_img_cyberpank_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGImg = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_BGImg, &ui_img_cyberpank_bg_png);
    lv_obj_set_width(ui_BGImg, LV_SIZE_CONTENT);   /// 702
    lv_obj_set_height(ui_BGImg, LV_SIZE_CONTENT);    /// 431
    lv_obj_set_x(ui_BGImg, 21);
    lv_obj_set_y(ui_BGImg, 72);
    lv_obj_set_align(ui_BGImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BGImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerLicuidGlass = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_RollerLicuidGlass, 140);
    lv_obj_set_height(ui_RollerLicuidGlass, 129);
    lv_obj_set_x(ui_RollerLicuidGlass, -76);
    lv_obj_set_y(ui_RollerLicuidGlass, 25);
    lv_obj_set_align(ui_RollerLicuidGlass, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RollerLicuidGlass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RollerLicuidGlass, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerLicuidGlass, lv_color_hex(0x8D8D8D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerLicuidGlass, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerLicuidGlass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerLicuidGlass, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RollerLicuidGlass, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RollerLicuidGlass, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RollerLicuidGlass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RollerLicuidGlass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RollerLicuidGlass, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RollerLicuidGlass, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_RollerLicuidGlass);
    lv_roller_set_options(ui_Roller1, "Sensors\nBLE\nWIFI\nRFID", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 0);
    lv_obj_set_y(ui_Roller1, -1);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x030202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0xE80707), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_16, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x9D9CA0), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Roller1);
    lv_obj_set_width(ui_Panel2, 80);
    lv_obj_set_height(ui_Panel2, 30);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -33);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Roller1);
    lv_obj_set_width(ui_Panel1, 80);
    lv_obj_set_height(ui_Panel1, 30);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 32);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoLicuidGlass = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_InfoLicuidGlass, 117);
    lv_obj_set_height(ui_InfoLicuidGlass, 142);
    lv_obj_set_x(ui_InfoLicuidGlass, 88);
    lv_obj_set_y(ui_InfoLicuidGlass, 21);
    lv_obj_set_align(ui_InfoLicuidGlass, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InfoLicuidGlass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_InfoLicuidGlass, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InfoLicuidGlass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InfoLicuidGlass, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_InfoLicuidGlass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_InfoLicuidGlass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_InfoLicuidGlass, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_InfoLicuidGlass, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainIfonLabel = lv_label_create(ui_InfoLicuidGlass);
    lv_obj_set_width(ui_MainIfonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainIfonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainIfonLabel, 1);
    lv_obj_set_y(ui_MainIfonLabel, -53);
    lv_obj_set_align(ui_MainIfonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainIfonLabel, "Main Info");

    ui_Container6 = lv_obj_create(ui_InfoLicuidGlass);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 56);
    lv_obj_set_height(ui_Container6, 82);
    lv_obj_set_x(ui_Container6, -24);
    lv_obj_set_y(ui_Container6, 8);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "Temp:");

    ui_HumLabel = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_HumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel, "Hum:");

    ui_PressLabel = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_PressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressLabel, "Press:");

    ui_Container7 = lv_obj_create(ui_InfoLicuidGlass);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 48);
    lv_obj_set_height(ui_Container7, 83);
    lv_obj_set_x(ui_Container7, 26);
    lv_obj_set_y(ui_Container7, 8);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempValLabel = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_TempValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempValLabel, "0.0");

    ui_HumValLabel = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_HumValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumValLabel, "0.0");

    ui_PressValLabel = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_PressValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressValLabel, "0.0");

    ui_BatChargeBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_value(ui_BatChargeBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatChargeBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatChargeBar, 34);
    lv_obj_set_height(ui_BatChargeBar, 10);
    lv_obj_set_x(ui_BatChargeBar, -136);
    lv_obj_set_y(ui_BatChargeBar, -108);
    lv_obj_set_align(ui_BatChargeBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BatChargeBar, lv_color_hex(0x1A1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatChargeBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BatChargeBar, lv_color_hex(0x00FFCB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatChargeBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BatChargeLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BatChargeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatChargeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatChargeLabel, -97);
    lv_obj_set_y(ui_BatChargeLabel, -108);
    lv_obj_set_align(ui_BatChargeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatChargeLabel, "0.0");

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_BGImg = NULL;
    ui_RollerLicuidGlass = NULL;
    ui_Roller1 = NULL;
    ui_Panel2 = NULL;
    ui_Panel1 = NULL;
    ui_InfoLicuidGlass = NULL;
    ui_MainIfonLabel = NULL;
    ui_Container6 = NULL;
    ui_TempLabel = NULL;
    ui_HumLabel = NULL;
    ui_PressLabel = NULL;
    ui_Container7 = NULL;
    ui_TempValLabel = NULL;
    ui_HumValLabel = NULL;
    ui_PressValLabel = NULL;
    ui_BatChargeBar = NULL;
    ui_BatChargeLabel = NULL;

}
