// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_uiMenuCarousel = NULL;
lv_obj_t * ui_uiHomePanel = NULL;
lv_obj_t * ui_BatLabel = NULL;
lv_obj_t * ui_BatValLabel = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_TempValLabel = NULL;
lv_obj_t * ui_HumLabel = NULL;
lv_obj_t * ui_HumValLabel = NULL;
lv_obj_t * ui_PressLabel = NULL;
lv_obj_t * ui_PressValLabel = NULL;
lv_obj_t * ui_uiRFIDPanel = NULL;
lv_obj_t * ui_BackButton = NULL;
lv_obj_t * ui_BackLabel = NULL;
lv_obj_t * ui_ReadBtn = NULL;
lv_obj_t * ui_SearchLabel = NULL;
lv_obj_t * ui_RFIDTagLabel = NULL;
lv_obj_t * ui_EmulateBtn = NULL;
lv_obj_t * ui_EmulateLabel = NULL;
lv_obj_t * ui_TagSelectRoller = NULL;
lv_obj_t * ui_uiWiFiPanel = NULL;
lv_obj_t * ui_BackButtonWiFi = NULL;
lv_obj_t * ui_BackLabelWiFI = NULL;
lv_obj_t * ui_ScanWiFiBut = NULL;
lv_obj_t * ui_ScanWiFiLabel = NULL;
lv_obj_t * ui_NetListRoller = NULL;
lv_obj_t * ui_PortScanBtn = NULL;
lv_obj_t * ui_PortScanLabel = NULL;
lv_obj_t * ui_EvilTwinBtn = NULL;
lv_obj_t * ui_EvilTwinLabel = NULL;
lv_obj_t * ui_StartBtn = NULL;
lv_obj_t * ui_StartLabel = NULL;
lv_obj_t * ui_uiBTPanel = NULL;
lv_obj_t * ui_BLEBackBtn = NULL;
lv_obj_t * ui_BLEBackLabel = NULL;
lv_obj_t * ui_BLEFloodBtn = NULL;
lv_obj_t * ui_BLEFloodLabel = NULL;
lv_obj_t * ui_BTHIDBtn = NULL;
lv_obj_t * ui_BTIDdLabel = NULL;
lv_obj_t * ui_BTScan = NULL;
lv_obj_t * ui_BTScanLabel = NULL;
lv_obj_t * ui_BLEDataRoller = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Screen1, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_Screen1, LV_SCROLL_SNAP_CENTER);

    ui_uiMenuCarousel = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_uiMenuCarousel);
    lv_obj_set_width(ui_uiMenuCarousel, 320);
    lv_obj_set_height(ui_uiMenuCarousel, 240);
    lv_obj_set_align(ui_uiMenuCarousel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiMenuCarousel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiMenuCarousel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_uiMenuCarousel, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_uiMenuCarousel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_scroll_dir(ui_uiMenuCarousel, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_uiMenuCarousel, LV_SCROLL_SNAP_CENTER);

    ui_uiHomePanel = lv_obj_create(ui_uiMenuCarousel);
    lv_obj_set_width(ui_uiHomePanel, 320);
    lv_obj_set_height(ui_uiHomePanel, 240);
    lv_obj_set_x(ui_uiHomePanel, 0);
    lv_obj_set_y(ui_uiHomePanel, -2);
    lv_obj_set_align(ui_uiHomePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiHomePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiHomePanel, lv_color_hex(0x0E002E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiHomePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatLabel = lv_label_create(ui_uiHomePanel);
    lv_obj_set_width(ui_BatLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatLabel, 75);
    lv_obj_set_y(ui_BatLabel, -99);
    lv_obj_set_align(ui_BatLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatLabel, "Bat:");
    lv_obj_set_style_text_color(ui_BatLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatValLabel = lv_label_create(ui_uiHomePanel);
    lv_obj_set_width(ui_BatValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatValLabel, 119);
    lv_obj_set_y(ui_BatValLabel, -99);
    lv_obj_set_align(ui_BatValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatValLabel, "0.0");
    lv_obj_set_style_text_color(ui_BatValLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatValLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatValLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_uiHomePanel);
    lv_obj_set_width(ui_TimeLabel, 120);
    lv_obj_set_height(ui_TimeLabel, 44);
    lv_obj_set_y(ui_TimeLabel, -8);
    lv_obj_set_x(ui_TimeLabel, lv_pct(-2));
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "00:00");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_uiHomePanel);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 147);
    lv_obj_set_height(ui_Container2, 42);
    lv_obj_set_x(ui_Container2, -69);
    lv_obj_set_y(ui_Container2, -83);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, -90);
    lv_obj_set_y(ui_TempLabel, 61);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "Temp");
    lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempValLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_TempValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempValLabel, -94);
    lv_obj_set_y(ui_TempValLabel, 88);
    lv_obj_set_align(ui_TempValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempValLabel, "0.0");
    lv_obj_set_style_text_color(ui_TempValLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempValLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_HumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumLabel, -12);
    lv_obj_set_y(ui_HumLabel, 60);
    lv_obj_set_align(ui_HumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel, "Hum");
    lv_obj_set_style_text_color(ui_HumLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumValLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_HumValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumValLabel, -19);
    lv_obj_set_y(ui_HumValLabel, 87);
    lv_obj_set_align(ui_HumValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumValLabel, "0.0");
    lv_obj_set_style_text_color(ui_HumValLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumValLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_PressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressLabel, 67);
    lv_obj_set_y(ui_PressLabel, 59);
    lv_obj_set_align(ui_PressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressLabel, "Press");
    lv_obj_set_style_text_color(ui_PressLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressValLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_PressValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressValLabel, 70);
    lv_obj_set_y(ui_PressValLabel, 86);
    lv_obj_set_align(ui_PressValLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PressValLabel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PressValLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PressValLabel, "0.0");
    lv_obj_set_style_text_color(ui_PressValLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressValLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiRFIDPanel = lv_obj_create(ui_uiMenuCarousel);
    lv_obj_set_width(ui_uiRFIDPanel, 320);
    lv_obj_set_height(ui_uiRFIDPanel, 240);
    lv_obj_set_x(ui_uiRFIDPanel, 1);
    lv_obj_set_y(ui_uiRFIDPanel, 0);
    lv_obj_set_align(ui_uiRFIDPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiRFIDPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiRFIDPanel, lv_color_hex(0x0E002E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiRFIDPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_btn_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_BackButton, 49);
    lv_obj_set_height(ui_BackButton, 21);
    lv_obj_set_x(ui_BackButton, -4);
    lv_obj_set_y(ui_BackButton, -7);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackLabel = lv_label_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_BackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackLabel, -124);
    lv_obj_set_y(ui_BackLabel, -102);
    lv_obj_set_align(ui_BackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabel, "Back");

    ui_ReadBtn = lv_btn_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_ReadBtn, 127);
    lv_obj_set_height(ui_ReadBtn, 50);
    lv_obj_set_x(ui_ReadBtn, -79);
    lv_obj_set_y(ui_ReadBtn, -49);
    lv_obj_set_align(ui_ReadBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReadBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ReadBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ReadBtn, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReadBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SearchLabel = lv_label_create(ui_ReadBtn);
    lv_obj_set_width(ui_SearchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SearchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SearchLabel, 2);
    lv_obj_set_y(ui_SearchLabel, -1);
    lv_obj_set_align(ui_SearchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SearchLabel, "Read card");
    lv_obj_set_style_text_font(ui_SearchLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFIDTagLabel = lv_label_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_RFIDTagLabel, 121);
    lv_obj_set_height(ui_RFIDTagLabel, 45);
    lv_obj_set_x(ui_RFIDTagLabel, -82);
    lv_obj_set_y(ui_RFIDTagLabel, 32);
    lv_obj_set_align(ui_RFIDTagLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RFIDTagLabel, "press \"Read Card\"");
    lv_obj_set_style_text_color(ui_RFIDTagLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RFIDTagLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmulateBtn = lv_btn_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_EmulateBtn, 127);
    lv_obj_set_height(ui_EmulateBtn, 50);
    lv_obj_set_x(ui_EmulateBtn, 77);
    lv_obj_set_y(ui_EmulateBtn, -50);
    lv_obj_set_align(ui_EmulateBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EmulateBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EmulateBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EmulateBtn, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EmulateBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmulateLabel = lv_label_create(ui_EmulateBtn);
    lv_obj_set_width(ui_EmulateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmulateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EmulateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EmulateLabel, "Emulate card");
    lv_obj_set_style_text_font(ui_EmulateLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TagSelectRoller = lv_roller_create(ui_uiRFIDPanel);
    lv_roller_set_options(ui_TagSelectRoller, "no Tag to\nemulate", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_TagSelectRoller, 82);
    lv_obj_set_width(ui_TagSelectRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_TagSelectRoller, 66);
    lv_obj_set_y(ui_TagSelectRoller, 40);
    lv_obj_set_align(ui_TagSelectRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TagSelectRoller, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TagSelectRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TagSelectRoller, lv_color_hex(0x2D27A8), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TagSelectRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_uiWiFiPanel = lv_obj_create(ui_uiMenuCarousel);
    lv_obj_set_width(ui_uiWiFiPanel, 320);
    lv_obj_set_height(ui_uiWiFiPanel, 240);
    lv_obj_set_x(ui_uiWiFiPanel, 4);
    lv_obj_set_y(ui_uiWiFiPanel, -4);
    lv_obj_set_align(ui_uiWiFiPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiWiFiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiWiFiPanel, lv_color_hex(0x0E002E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiWiFiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtonWiFi = lv_btn_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_BackButtonWiFi, 49);
    lv_obj_set_height(ui_BackButtonWiFi, 21);
    lv_obj_set_x(ui_BackButtonWiFi, -122);
    lv_obj_set_y(ui_BackButtonWiFi, -98);
    lv_obj_set_align(ui_BackButtonWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtonWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButtonWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButtonWiFi, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtonWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackLabelWiFI = lv_label_create(ui_BackButtonWiFi);
    lv_obj_set_width(ui_BackLabelWiFI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabelWiFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackLabelWiFI, 1);
    lv_obj_set_y(ui_BackLabelWiFI, 2);
    lv_obj_set_align(ui_BackLabelWiFI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabelWiFI, "Back");

    ui_ScanWiFiBut = lv_btn_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_ScanWiFiBut, 81);
    lv_obj_set_height(ui_ScanWiFiBut, 21);
    lv_obj_set_x(ui_ScanWiFiBut, -32);
    lv_obj_set_y(ui_ScanWiFiBut, -99);
    lv_obj_set_align(ui_ScanWiFiBut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScanWiFiBut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScanWiFiBut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScanWiFiBut, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScanWiFiBut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScanWiFiLabel = lv_label_create(ui_ScanWiFiBut);
    lv_obj_set_width(ui_ScanWiFiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanWiFiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScanWiFiLabel, 3);
    lv_obj_set_y(ui_ScanWiFiLabel, 0);
    lv_obj_set_align(ui_ScanWiFiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScanWiFiLabel, "WiFi Scan");

    ui_NetListRoller = lv_roller_create(ui_uiWiFiPanel);
    lv_roller_set_options(ui_NetListRoller, "empty", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_NetListRoller, 122);
    lv_obj_set_height(ui_NetListRoller, 113);
    lv_obj_set_x(ui_NetListRoller, -85);
    lv_obj_set_y(ui_NetListRoller, 0);
    lv_obj_set_align(ui_NetListRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_NetListRoller, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetListRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NetListRoller, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NetListRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NetListRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NetListRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NetListRoller, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_NetListRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetListRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_NetListRoller, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NetListRoller, lv_color_hex(0x2D27A8), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NetListRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PortScanBtn = lv_btn_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_PortScanBtn, 70);
    lv_obj_set_height(ui_PortScanBtn, 21);
    lv_obj_set_x(ui_PortScanBtn, 62);
    lv_obj_set_y(ui_PortScanBtn, -70);
    lv_obj_set_align(ui_PortScanBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PortScanBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PortScanBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PortScanBtn, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PortScanBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PortScanLabel = lv_label_create(ui_PortScanBtn);
    lv_obj_set_width(ui_PortScanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PortScanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PortScanLabel, -1);
    lv_obj_set_y(ui_PortScanLabel, 0);
    lv_obj_set_align(ui_PortScanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PortScanLabel, "Port Scan");
    lv_obj_set_style_text_font(ui_PortScanLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EvilTwinBtn = lv_btn_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_EvilTwinBtn, 67);
    lv_obj_set_height(ui_EvilTwinBtn, 21);
    lv_obj_set_x(ui_EvilTwinBtn, 60);
    lv_obj_set_y(ui_EvilTwinBtn, -101);
    lv_obj_set_align(ui_EvilTwinBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EvilTwinBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EvilTwinBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EvilTwinBtn, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EvilTwinBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EvilTwinLabel = lv_label_create(ui_EvilTwinBtn);
    lv_obj_set_width(ui_EvilTwinLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EvilTwinLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EvilTwinLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EvilTwinLabel, "Evil Twin");

    ui_StartBtn = lv_btn_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_StartBtn, 100);
    lv_obj_set_height(ui_StartBtn, 39);
    lv_obj_set_x(ui_StartBtn, 66);
    lv_obj_set_y(ui_StartBtn, 2);
    lv_obj_set_align(ui_StartBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartBtn, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartLabel = lv_label_create(ui_StartBtn);
    lv_obj_set_width(ui_StartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartLabel, -1);
    lv_obj_set_y(ui_StartLabel, -1);
    lv_obj_set_align(ui_StartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartLabel, "Start");

    ui_uiBTPanel = lv_obj_create(ui_uiMenuCarousel);
    lv_obj_set_width(ui_uiBTPanel, 320);
    lv_obj_set_height(ui_uiBTPanel, 240);
    lv_obj_set_align(ui_uiBTPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiBTPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiBTPanel, lv_color_hex(0x0E002E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiBTPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLEBackBtn = lv_btn_create(ui_uiBTPanel);
    lv_obj_set_width(ui_BLEBackBtn, 49);
    lv_obj_set_height(ui_BLEBackBtn, 21);
    lv_obj_set_x(ui_BLEBackBtn, -121);
    lv_obj_set_y(ui_BLEBackBtn, -96);
    lv_obj_set_align(ui_BLEBackBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLEBackBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLEBackBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLEBackBtn, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLEBackBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLEBackLabel = lv_label_create(ui_BLEBackBtn);
    lv_obj_set_width(ui_BLEBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLEBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BLEBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLEBackLabel, "Back");

    ui_BLEFloodBtn = lv_btn_create(ui_uiBTPanel);
    lv_obj_set_width(ui_BLEFloodBtn, 73);
    lv_obj_set_height(ui_BLEFloodBtn, 21);
    lv_obj_set_x(ui_BLEFloodBtn, -47);
    lv_obj_set_y(ui_BLEFloodBtn, -96);
    lv_obj_set_align(ui_BLEFloodBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BLEFloodBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BLEFloodBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLEFloodBtn, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLEFloodBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLEFloodLabel = lv_label_create(ui_BLEFloodBtn);
    lv_obj_set_width(ui_BLEFloodLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLEFloodLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BLEFloodLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLEFloodLabel, "BLE Flood");

    ui_BTHIDBtn = lv_btn_create(ui_uiBTPanel);
    lv_obj_set_width(ui_BTHIDBtn, 58);
    lv_obj_set_height(ui_BTHIDBtn, 21);
    lv_obj_set_x(ui_BTHIDBtn, 28);
    lv_obj_set_y(ui_BTHIDBtn, -95);
    lv_obj_set_align(ui_BTHIDBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTHIDBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTHIDBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTHIDBtn, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTHIDBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIDdLabel = lv_label_create(ui_BTHIDBtn);
    lv_obj_set_width(ui_BTIDdLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIDdLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIDdLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BTIDdLabel, "BT HID");

    ui_BTScan = lv_btn_create(ui_uiBTPanel);
    lv_obj_set_width(ui_BTScan, 64);
    lv_obj_set_height(ui_BTScan, 21);
    lv_obj_set_x(ui_BTScan, 107);
    lv_obj_set_y(ui_BTScan, -93);
    lv_obj_set_align(ui_BTScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTScan, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTScanLabel = lv_label_create(ui_BTScan);
    lv_obj_set_width(ui_BTScanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTScanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTScanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BTScanLabel, "BT Scan");

    ui_BLEDataRoller = lv_roller_create(ui_uiBTPanel);
    lv_roller_set_options(ui_BLEDataRoller, "no BLE\ndetected", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_BLEDataRoller, 100);
    lv_obj_set_width(ui_BLEDataRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BLEDataRoller, -74);
    lv_obj_set_y(ui_BLEDataRoller, 21);
    lv_obj_set_align(ui_BLEDataRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BLEDataRoller, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLEDataRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BLEDataRoller, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BLEDataRoller, lv_color_hex(0x2D27A8), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLEDataRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_uiMenuCarousel = NULL;
    ui_uiHomePanel = NULL;
    ui_BatLabel = NULL;
    ui_BatValLabel = NULL;
    ui_TimeLabel = NULL;
    ui_Container2 = NULL;
    ui_TempLabel = NULL;
    ui_TempValLabel = NULL;
    ui_HumLabel = NULL;
    ui_HumValLabel = NULL;
    ui_PressLabel = NULL;
    ui_PressValLabel = NULL;
    ui_uiRFIDPanel = NULL;
    ui_BackButton = NULL;
    ui_BackLabel = NULL;
    ui_ReadBtn = NULL;
    ui_SearchLabel = NULL;
    ui_RFIDTagLabel = NULL;
    ui_EmulateBtn = NULL;
    ui_EmulateLabel = NULL;
    ui_TagSelectRoller = NULL;
    ui_uiWiFiPanel = NULL;
    ui_BackButtonWiFi = NULL;
    ui_BackLabelWiFI = NULL;
    ui_ScanWiFiBut = NULL;
    ui_ScanWiFiLabel = NULL;
    ui_NetListRoller = NULL;
    ui_PortScanBtn = NULL;
    ui_PortScanLabel = NULL;
    ui_EvilTwinBtn = NULL;
    ui_EvilTwinLabel = NULL;
    ui_StartBtn = NULL;
    ui_StartLabel = NULL;
    ui_uiBTPanel = NULL;
    ui_BLEBackBtn = NULL;
    ui_BLEBackLabel = NULL;
    ui_BLEFloodBtn = NULL;
    ui_BLEFloodLabel = NULL;
    ui_BTHIDBtn = NULL;
    ui_BTIDdLabel = NULL;
    ui_BTScan = NULL;
    ui_BTScanLabel = NULL;
    ui_BLEDataRoller = NULL;

}
