// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SENSORSSCREEN_H
#define UI_SENSORSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorsScreen
extern void ui_SensorsScreen_screen_init(void);
extern void ui_SensorsScreen_screen_destroy(void);
extern lv_obj_t * ui_SensorsScreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

