// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_uiMenuCarousel = NULL;
lv_obj_t * ui_uiHomePanel = NULL;
lv_obj_t * ui_BatLabel = NULL;
lv_obj_t * ui_BatValLabel = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_RFIDLabel = NULL;
lv_obj_t * ui_NFCLabel = NULL;
lv_obj_t * ui_WiFiLabel = NULL;
lv_obj_t * ui_RFIDStatusLabel = NULL;
lv_obj_t * ui_NFCStatusLabel = NULL;
lv_obj_t * ui_WiFiStatusLabel = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_TempValLabel = NULL;
lv_obj_t * ui_HumLabel = NULL;
lv_obj_t * ui_HumValLabel = NULL;
lv_obj_t * ui_PressLabel = NULL;
lv_obj_t * ui_PressValLabel = NULL;
lv_obj_t * ui_uiRFIDPanel = NULL;
lv_obj_t * ui_BackButton = NULL;
lv_obj_t * ui_BackLabel = NULL;
lv_obj_t * ui_OnButton = NULL;
lv_obj_t * ui_OnLabel = NULL;
lv_obj_t * ui_SearchButton = NULL;
lv_obj_t * ui_SearchLabel = NULL;
lv_obj_t * ui_OutputLabel = NULL;
lv_obj_t * ui_OffButton = NULL;
lv_obj_t * ui_OffLabel = NULL;
lv_obj_t * ui_uiWiFiPanel = NULL;
lv_obj_t * ui_BackButtonWiFi = NULL;
lv_obj_t * ui_BackLabelWiFI = NULL;
lv_obj_t * ui_NetTextArea = NULL;
lv_obj_t * ui_NetLabel = NULL;
lv_obj_t * ui_OnButtonWiFi = NULL;
lv_obj_t * ui_OffButtonWiFi = NULL;
lv_obj_t * ui_OnLabelWiFi = NULL;
lv_obj_t * ui_OffLabelWiFi = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiMenuCarousel = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_uiMenuCarousel);
    lv_obj_set_width(ui_uiMenuCarousel, 320);
    lv_obj_set_height(ui_uiMenuCarousel, 240);
    lv_obj_set_align(ui_uiMenuCarousel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiMenuCarousel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_uiMenuCarousel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_uiMenuCarousel, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_uiMenuCarousel, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_uiMenuCarousel, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_uiMenuCarousel, LV_SCROLL_SNAP_CENTER);

    ui_uiHomePanel = lv_obj_create(ui_uiMenuCarousel);
    lv_obj_set_width(ui_uiHomePanel, 320);
    lv_obj_set_height(ui_uiHomePanel, 240);
    lv_obj_set_x(ui_uiHomePanel, 0);
    lv_obj_set_y(ui_uiHomePanel, -2);
    lv_obj_set_align(ui_uiHomePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiHomePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiHomePanel, lv_color_hex(0x0E002E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiHomePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatLabel = lv_label_create(ui_uiHomePanel);
    lv_obj_set_width(ui_BatLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatLabel, 75);
    lv_obj_set_y(ui_BatLabel, -99);
    lv_obj_set_align(ui_BatLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatLabel, "Bat:");
    lv_obj_set_style_text_color(ui_BatLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatValLabel = lv_label_create(ui_uiHomePanel);
    lv_obj_set_width(ui_BatValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatValLabel, 119);
    lv_obj_set_y(ui_BatValLabel, -99);
    lv_obj_set_align(ui_BatValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatValLabel, "0.0");
    lv_obj_set_style_text_color(ui_BatValLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatValLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatValLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_uiHomePanel);
    lv_obj_set_width(ui_TimeLabel, 120);
    lv_obj_set_height(ui_TimeLabel, 44);
    lv_obj_set_y(ui_TimeLabel, -2);
    lv_obj_set_x(ui_TimeLabel, lv_pct(-1));
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "00:00");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_uiHomePanel);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 81);
    lv_obj_set_height(ui_Container1, 53);
    lv_obj_set_x(ui_Container1, -109);
    lv_obj_set_y(ui_Container1, -81);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFIDLabel = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_RFIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RFIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RFIDLabel, -127);
    lv_obj_set_y(ui_RFIDLabel, -77);
    lv_obj_set_align(ui_RFIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RFIDLabel, "RFID");
    lv_obj_set_style_text_color(ui_RFIDLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RFIDLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NFCLabel = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_NFCLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NFCLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NFCLabel, -128);
    lv_obj_set_y(ui_NFCLabel, -51);
    lv_obj_set_align(ui_NFCLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NFCLabel, "NFC");
    lv_obj_set_style_text_color(ui_NFCLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NFCLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiLabel = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_WiFiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiLabel, -126);
    lv_obj_set_y(ui_WiFiLabel, -101);
    lv_obj_set_align(ui_WiFiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiLabel, "WiFi");
    lv_obj_set_style_text_color(ui_WiFiLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFIDStatusLabel = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_RFIDStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RFIDStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RFIDStatusLabel, -85);
    lv_obj_set_y(ui_RFIDStatusLabel, -77);
    lv_obj_set_align(ui_RFIDStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RFIDStatusLabel, "off");
    lv_obj_set_style_text_color(ui_RFIDStatusLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RFIDStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NFCStatusLabel = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_NFCStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NFCStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NFCStatusLabel, -85);
    lv_obj_set_y(ui_NFCStatusLabel, -51);
    lv_obj_set_align(ui_NFCStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NFCStatusLabel, "off");
    lv_obj_set_style_text_color(ui_NFCStatusLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NFCStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiStatusLabel = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_WiFiStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatusLabel, -86);
    lv_obj_set_y(ui_WiFiStatusLabel, -102);
    lv_obj_set_align(ui_WiFiStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiStatusLabel, "off");
    lv_obj_set_style_text_color(ui_WiFiStatusLabel, lv_color_hex(0xFF0011), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_uiHomePanel);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 147);
    lv_obj_set_height(ui_Container2, 42);
    lv_obj_set_x(ui_Container2, -3);
    lv_obj_set_y(ui_Container2, 69);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, -90);
    lv_obj_set_y(ui_TempLabel, 61);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "Temp");
    lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempValLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_TempValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempValLabel, -94);
    lv_obj_set_y(ui_TempValLabel, 88);
    lv_obj_set_align(ui_TempValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempValLabel, "0.0");
    lv_obj_set_style_text_color(ui_TempValLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempValLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_HumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumLabel, -12);
    lv_obj_set_y(ui_HumLabel, 60);
    lv_obj_set_align(ui_HumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel, "Hum");
    lv_obj_set_style_text_color(ui_HumLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumValLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_HumValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumValLabel, -19);
    lv_obj_set_y(ui_HumValLabel, 87);
    lv_obj_set_align(ui_HumValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumValLabel, "0.0");
    lv_obj_set_style_text_color(ui_HumValLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumValLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_PressLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressLabel, 67);
    lv_obj_set_y(ui_PressLabel, 59);
    lv_obj_set_align(ui_PressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressLabel, "Press");
    lv_obj_set_style_text_color(ui_PressLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressValLabel = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_PressValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressValLabel, 70);
    lv_obj_set_y(ui_PressValLabel, 86);
    lv_obj_set_align(ui_PressValLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PressValLabel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PressValLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PressValLabel, "0.0");
    lv_obj_set_style_text_color(ui_PressValLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PressValLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiRFIDPanel = lv_obj_create(ui_uiMenuCarousel);
    lv_obj_set_width(ui_uiRFIDPanel, 320);
    lv_obj_set_height(ui_uiRFIDPanel, 240);
    lv_obj_set_align(ui_uiRFIDPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiRFIDPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiRFIDPanel, lv_color_hex(0x0E002E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiRFIDPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_btn_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_BackButton, 49);
    lv_obj_set_height(ui_BackButton, 21);
    lv_obj_set_x(ui_BackButton, -4);
    lv_obj_set_y(ui_BackButton, -7);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackLabel = lv_label_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_BackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackLabel, -124);
    lv_obj_set_y(ui_BackLabel, -102);
    lv_obj_set_align(ui_BackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabel, "Back");

    ui_OnButton = lv_btn_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_OnButton, 63);
    lv_obj_set_height(ui_OnButton, 30);
    lv_obj_set_x(ui_OnButton, -17);
    lv_obj_set_y(ui_OnButton, -98);
    lv_obj_set_align(ui_OnButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OnButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OnButton, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OnButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnLabel = lv_label_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_OnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnLabel, -17);
    lv_obj_set_y(ui_OnLabel, -98);
    lv_obj_set_align(ui_OnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnLabel, "turn on");

    ui_SearchButton = lv_btn_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_SearchButton, 100);
    lv_obj_set_height(ui_SearchButton, 50);
    lv_obj_set_x(ui_SearchButton, -18);
    lv_obj_set_y(ui_SearchButton, -33);
    lv_obj_set_align(ui_SearchButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SearchButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SearchButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SearchButton, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SearchButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SearchLabel = lv_label_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_SearchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SearchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SearchLabel, -17);
    lv_obj_set_y(ui_SearchLabel, -33);
    lv_obj_set_align(ui_SearchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SearchLabel, "Search...");
    lv_obj_set_style_text_font(ui_SearchLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OutputLabel = lv_label_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_OutputLabel, 100);
    lv_obj_set_height(ui_OutputLabel, 76);
    lv_obj_set_x(ui_OutputLabel, -15);
    lv_obj_set_y(ui_OutputLabel, 39);
    lv_obj_set_align(ui_OutputLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OutputLabel, "no card detected");
    lv_obj_set_style_text_color(ui_OutputLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OutputLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OffButton = lv_btn_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_OffButton, 63);
    lv_obj_set_height(ui_OffButton, 30);
    lv_obj_set_x(ui_OffButton, 99);
    lv_obj_set_y(ui_OffButton, -100);
    lv_obj_set_align(ui_OffButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OffButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OffButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OffButton, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OffButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OffLabel = lv_label_create(ui_uiRFIDPanel);
    lv_obj_set_width(ui_OffLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OffLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OffLabel, 99);
    lv_obj_set_y(ui_OffLabel, -100);
    lv_obj_set_align(ui_OffLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OffLabel, "turn off");

    ui_uiWiFiPanel = lv_obj_create(ui_uiMenuCarousel);
    lv_obj_set_width(ui_uiWiFiPanel, 320);
    lv_obj_set_height(ui_uiWiFiPanel, 240);
    lv_obj_set_x(ui_uiWiFiPanel, 4);
    lv_obj_set_y(ui_uiWiFiPanel, 0);
    lv_obj_set_align(ui_uiWiFiPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiWiFiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiWiFiPanel, lv_color_hex(0x0E002E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiWiFiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtonWiFi = lv_btn_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_BackButtonWiFi, 49);
    lv_obj_set_height(ui_BackButtonWiFi, 21);
    lv_obj_set_x(ui_BackButtonWiFi, -122);
    lv_obj_set_y(ui_BackButtonWiFi, -98);
    lv_obj_set_align(ui_BackButtonWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButtonWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButtonWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButtonWiFi, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButtonWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackLabelWiFI = lv_label_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_BackLabelWiFI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackLabelWiFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackLabelWiFI, -121);
    lv_obj_set_y(ui_BackLabelWiFI, -99);
    lv_obj_set_align(ui_BackLabelWiFI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackLabelWiFI, "Back");

    ui_NetTextArea = lv_textarea_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_NetTextArea, 123);
    lv_obj_set_height(ui_NetTextArea, 140);
    lv_obj_set_x(ui_NetTextArea, -74);
    lv_obj_set_y(ui_NetTextArea, 23);
    lv_obj_set_align(ui_NetTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_NetTextArea, 1000);

    ui_NetLabel = lv_label_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_NetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetLabel, -75);
    lv_obj_set_y(ui_NetLabel, -61);
    lv_obj_set_align(ui_NetLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetLabel, "available network");
    lv_obj_set_style_text_color(ui_NetLabel, lv_color_hex(0x00D9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnButtonWiFi = lv_btn_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_OnButtonWiFi, 63);
    lv_obj_set_height(ui_OnButtonWiFi, 30);
    lv_obj_set_x(ui_OnButtonWiFi, -21);
    lv_obj_set_y(ui_OnButtonWiFi, -95);
    lv_obj_set_align(ui_OnButtonWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnButtonWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OnButtonWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OnButtonWiFi, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OnButtonWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OffButtonWiFi = lv_btn_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_OffButtonWiFi, 63);
    lv_obj_set_height(ui_OffButtonWiFi, 30);
    lv_obj_set_x(ui_OffButtonWiFi, 86);
    lv_obj_set_y(ui_OffButtonWiFi, -93);
    lv_obj_set_align(ui_OffButtonWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OffButtonWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OffButtonWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OffButtonWiFi, lv_color_hex(0x8C00EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OffButtonWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnLabelWiFi = lv_label_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_OnLabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnLabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnLabelWiFi, -19);
    lv_obj_set_y(ui_OnLabelWiFi, -94);
    lv_obj_set_align(ui_OnLabelWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnLabelWiFi, "Turn on");

    ui_OffLabelWiFi = lv_label_create(ui_uiWiFiPanel);
    lv_obj_set_width(ui_OffLabelWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OffLabelWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OffLabelWiFi, 87);
    lv_obj_set_y(ui_OffLabelWiFi, -93);
    lv_obj_set_align(ui_OffLabelWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OffLabelWiFi, "Turn off");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_uiMenuCarousel = NULL;
    ui_uiHomePanel = NULL;
    ui_BatLabel = NULL;
    ui_BatValLabel = NULL;
    ui_TimeLabel = NULL;
    ui_Container1 = NULL;
    ui_RFIDLabel = NULL;
    ui_NFCLabel = NULL;
    ui_WiFiLabel = NULL;
    ui_RFIDStatusLabel = NULL;
    ui_NFCStatusLabel = NULL;
    ui_WiFiStatusLabel = NULL;
    ui_Container2 = NULL;
    ui_TempLabel = NULL;
    ui_TempValLabel = NULL;
    ui_HumLabel = NULL;
    ui_HumValLabel = NULL;
    ui_PressLabel = NULL;
    ui_PressValLabel = NULL;
    ui_uiRFIDPanel = NULL;
    ui_BackButton = NULL;
    ui_BackLabel = NULL;
    ui_OnButton = NULL;
    ui_OnLabel = NULL;
    ui_SearchButton = NULL;
    ui_SearchLabel = NULL;
    ui_OutputLabel = NULL;
    ui_OffButton = NULL;
    ui_OffLabel = NULL;
    ui_uiWiFiPanel = NULL;
    ui_BackButtonWiFi = NULL;
    ui_BackLabelWiFI = NULL;
    ui_NetTextArea = NULL;
    ui_NetLabel = NULL;
    ui_OnButtonWiFi = NULL;
    ui_OffButtonWiFi = NULL;
    ui_OnLabelWiFi = NULL;
    ui_OffLabelWiFi = NULL;

}
