// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_uiMenuCarousel;
extern lv_obj_t * ui_uiHomePanel;
extern lv_obj_t * ui_BatLabel;
extern lv_obj_t * ui_BatValLabel;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_TempValLabel;
extern lv_obj_t * ui_HumLabel;
extern lv_obj_t * ui_HumValLabel;
extern lv_obj_t * ui_PressLabel;
extern lv_obj_t * ui_PressValLabel;
extern lv_obj_t * ui_uiRFIDPanel;
extern lv_obj_t * ui_BackButton;
extern lv_obj_t * ui_BackLabel;
extern lv_obj_t * ui_SearchButton;
extern lv_obj_t * ui_SearchLabel;
extern lv_obj_t * ui_OutputLabel;
extern lv_obj_t * ui_uiWiFiPanel;
extern lv_obj_t * ui_BackButtonWiFi;
extern lv_obj_t * ui_BackLabelWiFI;
extern lv_obj_t * ui_ScanWiFiBut;
extern lv_obj_t * ui_ScanWiFiLabel;
extern lv_obj_t * ui_NetLabel;
extern lv_obj_t * ui_NetListRoller;
// CUSTOM VARIABLES
extern lv_obj_t * uic_NetListRoller;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

