// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_BatteryBar = NULL;
lv_obj_t * ui_MainInfoLabel = NULL;
lv_obj_t * ui_DataGrid = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_TempValLabel = NULL;
lv_obj_t * ui_HumLabel = NULL;
lv_obj_t * ui_HumValLabel = NULL;
lv_obj_t * ui_PressLabel = NULL;
lv_obj_t * ui_PressValLabel = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xEC006B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x9EF738), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, lv_pct(62));
    lv_obj_set_height(ui_Panel6, lv_pct(72));
    lv_obj_set_x(ui_Panel6, 3);
    lv_obj_set_y(ui_Panel6, -59);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x838383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel6, lv_color_hex(0x2B2B2B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel6, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_Roller1, "WiFi\nBLE\nSensors\nRFID", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Roller1, 141);
    lv_obj_set_height(ui_Roller1, 91);
    lv_obj_set_x(ui_Roller1, -59);
    lv_obj_set_y(ui_Roller1, -26);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0x75CB75), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x534D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0x4518D9), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_30, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x7F056F), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Roller1);
    lv_obj_set_width(ui_Panel9, 139);
    lv_obj_set_height(ui_Panel9, 25);
    lv_obj_set_x(ui_Panel9, 0);
    lv_obj_set_y(ui_Panel9, -33);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x451250), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Roller1);
    lv_obj_set_width(ui_Panel8, 141);
    lv_obj_set_height(ui_Panel8, 26);
    lv_obj_set_x(ui_Panel8, -1);
    lv_obj_set_y(ui_Panel8, 35);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x451250), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_BatteryBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBar, 38);
    lv_obj_set_height(ui_BatteryBar, 10);
    lv_obj_set_x(ui_BatteryBar, 112);
    lv_obj_set_y(ui_BatteryBar, -109);
    lv_obj_set_align(ui_BatteryBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0x010000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0xDE0AA3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MainInfoLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MainInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainInfoLabel, 99);
    lv_obj_set_y(ui_MainInfoLabel, -67);
    lv_obj_set_align(ui_MainInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainInfoLabel, "Main Info");

    ui_DataGrid = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_DataGrid);
    lv_obj_set_width(ui_DataGrid, 101);
    lv_obj_set_height(ui_DataGrid, 79);
    lv_obj_set_x(ui_DataGrid, 102);
    lv_obj_set_y(ui_DataGrid, -8);
    lv_obj_set_align(ui_DataGrid, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DataGrid, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_DataGrid, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_DataGrid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DataGrid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DataGrid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_DataGrid);
    lv_obj_set_width(ui_TempLabel, lv_pct(60));
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, 7);
    lv_obj_set_y(ui_TempLabel, -9);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "Temp:");

    ui_TempValLabel = lv_label_create(ui_DataGrid);
    lv_obj_set_width(ui_TempValLabel, lv_pct(40));
    lv_obj_set_height(ui_TempValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempValLabel, "0.0");

    ui_HumLabel = lv_label_create(ui_DataGrid);
    lv_obj_set_width(ui_HumLabel, lv_pct(60));
    lv_obj_set_height(ui_HumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumLabel, "Hum:");

    ui_HumValLabel = lv_label_create(ui_DataGrid);
    lv_obj_set_width(ui_HumValLabel, lv_pct(40));
    lv_obj_set_height(ui_HumValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumValLabel, "0.0");

    ui_PressLabel = lv_label_create(ui_DataGrid);
    lv_obj_set_width(ui_PressLabel, lv_pct(60));
    lv_obj_set_height(ui_PressLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressLabel, "Press:");

    ui_PressValLabel = lv_label_create(ui_DataGrid);
    lv_obj_set_width(ui_PressValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PressValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressValLabel, "0.0");

    uic_Screen1 = ui_Screen1;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    ui_Panel6 = NULL;
    ui_Roller1 = NULL;
    ui_Panel9 = NULL;
    ui_Panel8 = NULL;
    ui_BatteryBar = NULL;
    ui_MainInfoLabel = NULL;
    ui_DataGrid = NULL;
    ui_TempLabel = NULL;
    ui_TempValLabel = NULL;
    ui_HumLabel = NULL;
    ui_HumValLabel = NULL;
    ui_PressLabel = NULL;
    ui_PressValLabel = NULL;

}
