#ifndef _ONEWIRE_LIBRARY_H
#define _ONEWIRE_LIBRARY_H

#include "hardware/pio.h"
#include "hardware/clocks.h"            // for clock_get_hz() in generated header
#include "onewire_library.pio.h"        // generated by pioasm

// pin config
#define OW_PIN 14

// 1-Wire command
#define OW_READ_ROM         0x33
#define OW_MATCH_ROM        0x55
#define OW_SEARCHROM        0xF0
#define OW_ALARM_SEARCH     0xEC
#define OW_SKIP_ROM         0xCC

// DS18B20 command
#define DS18B20_CONVERT_T   0x44
#define DS18B20_READ_SCRATCHPAD 0xBE
#define DS18B20_WRITE_SCRATCHPAD 0x4E

typedef struct {
    PIO pio;
    uint sm;
    uint jmp_reset;
    int offset;
    int gpio;
} OW;

// init onewire
// bool ow_init (OW *ow, PIO pio, uint offset, uint gpio, uint sm);
void ow_init (OW *ow, PIO pio);

//
void ow_send (OW *ow, uint data);

//
uint8_t ow_read (OW *ow);

//
bool ow_reset (OW *ow);

//
int ow_romsearch (OW *ow, uint64_t *romcodes, int maxdevs, uint command);

#endif
